import type { Metadata } from "next";
import Link from "next/link";
import { EditorialPhoto } from "@/components/artwork";

export const metadata: Metadata = { title: "About Teens2Inspire", description: "A little more about the ideas, people, and purpose behind Teens2Inspire." };

export default function AboutPage() {
  return <main className="editorial-page"><section className="about-hero"><div><span className="eyebrow eyebrow-gold">A little about us</span><h1>Growing into<br /><em>your own story.</em></h1><p>Teens2Inspire is a place for Jewish teen girls to find thoughtful stories, bright ideas, honest voices, and the kind of encouragement that meets you where you are.</p><Link className="button button-primary" href="/discover">Explore the library <span aria-hidden="true">→</span></Link></div><EditorialPhoto src="https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=1050&q=85" alt="A young woman smiling in soft afternoon light" /></section><section className="about-principles"><div><span className="eyebrow">What we believe</span><h2>There is more than one way to <em>be becoming.</em></h2></div><div className="principle-grid"><article><span>01</span><h3>Your voice belongs here.</h3><p>There is room for your questions, your convictions, your humor, and the things you are still working out.</p></article><article><span>02</span><h3>Inspiration should feel real.</h3><p>Stories and ideas can open up new possibilities without pretending life is simple or perfectly polished.</p></article><article><span>03</span><h3>Jewish life is yours to grow into.</h3><p>We create with care for the many ways Jewish teens learn, celebrate, connect, and make meaning.</p></article></div></section><section className="about-safety"><span className="eyebrow eyebrow-gold">Thoughtful by design</span><h2>Belonging should<br /><em>feel safe.</em></h2><p>Teens2Inspire is designed with privacy in mind. Profiles stay private, community contributions are reviewed before they appear, and direct messages between members are not part of the experience.</p><Link href="/privacy" className="text-link">Read about privacy and safety <span aria-hidden="true">→</span></Link></section></main>;
}
